#ifndef TERRAIN_CONFIG_H
#define TERRAIN_CONFIG_H

//This should not be modified
#define TERRAIN_CHUNK_SIZE 64
#define TERRAIN_VOXELS_SSBO_BINDING 48

//Can be modified
#define TERRAIN_NUM_WORKER_THREADS 12
#define TERRAIN_GROUP_UPLOAD_LIMIT 4

#define TERRAIN_VIEW_RANGE 32
#define TERRAIN_HEIGHT 4
#define TERRAIN_LOWER_EDGE 1
#define TERRAIN_UPPER_EDGE 3

#define TERRAIN_MAX_GREEDY_AXIS 16

//region Caves
#define TERRAIN_CAVE_NOISE FNL_NOISE_PERLIN
#define TERRAIN_CAVE_FRACTAL FNL_FRACTAL_PINGPONG
#define TERRAIN_CAVE_FREQUENCY .01f
#define TERRAIN_CAVE_OCTAVES 4
#define TERRAIN_CAVE_GAIN .5f
#define TERRAIN_CAVE_LACUNARITY 2
#define TERRAIN_CAVE_PING_PONG_STRENGTH 2
//endregion

//region Flats
#define TERRAIN_FLAT_NOISE FNL_NOISE_VALUE_CUBIC
#define TERRAIN_FLAT_FRACTAL FNL_FRACTAL_FBM
#define TERRAIN_FLAT_FREQUENCY .01f
#define TERRAIN_FLAT_OCTAVES 6
#define TERRAIN_FLAT_GAIN .5f
#define TERRAIN_FLAT_LACUNARITY 2
//endregion

//region Small Hills
#define TERRAIN_SMALL_HILL_NOISE FNL_NOISE_VALUE
#define TERRAIN_SMALL_HILL_FRACTAL FNL_FRACTAL_FBM
#define TERRAIN_SMALL_HILL_FREQUENCY .01f
#define TERRAIN_SMALL_HILL_OCTAVES 6
#define TERRAIN_SMALL_HILL_GAIN .5f
#define TERRAIN_SMALL_HILL_LACUNARITY 2
//endregion

//region Hills
#define TERRAIN_HILL_NOISE FNL_NOISE_PERLIN
#define TERRAIN_HILL_FRACTAL FNL_FRACTAL_FBM
#define TERRAIN_HILL_FREQUENCY .01f
#define TERRAIN_HILL_OCTAVES 6
#define TERRAIN_HILL_GAIN .5f
#define TERRAIN_HILL_LACUNARITY 2
//endregion

//region Mountains
#define TERRAIN_MOUNTAIN_NOISE FNL_NOISE_OPENSIMPLEX2S
#define TERRAIN_MOUNTAIN_FRACTAL FNL_FRACTAL_FBM
#define TERRAIN_MOUNTAIN_FREQUENCY .01f
#define TERRAIN_MOUNTAIN_OCTAVES 6
#define TERRAIN_MOUNTAIN_GAIN .5f
#define TERRAIN_MOUNTAIN_LACUNARITY 2
//endregion

//region High Mountains
#define TERRAIN_HIGH_MOUNTAIN_NOISE FNL_NOISE_OPENSIMPLEX2
#define TERRAIN_HIGH_MOUNTAIN_FRACTAL FNL_FRACTAL_FBM
#define TERRAIN_HIGH_MOUNTAIN_FREQUENCY .01f
#define TERRAIN_HIGH_MOUNTAIN_OCTAVES 6
#define TERRAIN_HIGH_MOUNTAIN_GAIN .5f
#define TERRAIN_HIGH_MOUNTAIN_LACUNARITY 2
//endregion

#define TERRAIN_LOADING_EDGE 3

#define TERRAIN_MAX_AXIS_BLOCK_TYPES 16
#define TERRAIN_MAX_BLOCK_TYPES (TERRAIN_MAX_AXIS_BLOCK_TYPES * TERRAIN_MAX_AXIS_BLOCK_TYPES)

#define TERRAIN_CAVE_EDGE (-.7f)
#define TERRAIN_WORLD_EDGE 100000
#define TERRAIN_DELAYED_LOAD

#endif //TERRAIN_CONFIG_H
